import { renderEmail } from "./email-layout";

/**
 * Supabase Auth sends these through Brevo SMTP. Its Go-template placeholders are
 * left verbatim for Supabase to fill. Links open /auth/confirm, which spends the
 * token only when the person presses the button (link scanners open links first).
 *
 * The committed files in supabase/templates/ are regenerated by
 * `pnpm vitest run -u src/modules/notifications/email/auth-email-templates.test.ts`
 * and pasted into the Supabase dashboard (Auth → Email Templates).
 */
const SITE = "{{ .SiteURL }}";
const confirmUrl = (type: "email" | "recovery") =>
  `${SITE}/auth/confirm?token_hash={{ .TokenHash }}&type=${type}`;

export function renderAuthEmailTemplate(kind: "confirmation" | "recovery"): string {
  if (kind === "confirmation") {
    return renderEmail(
      {
        subject: "Confirm your VAULTIX email",
        preview: "Confirm your VAULTIX email address",
        heading: "Confirm your email",
        paragraphs: [
          "Press the button to confirm this address belongs to you. The link works once and expires in 1 hour.",
          "If you did not create a VAULTIX account, ignore this email.",
        ],
        action: { label: "Confirm my email", href: confirmUrl("email") },
      },
      SITE,
    ).html;
  }
  return renderEmail(
    {
      subject: "Reset your VAULTIX password",
      preview: "Reset your VAULTIX password",
      heading: "Reset your password",
      paragraphs: [
        "Press the button to choose a new password. The link works once and expires in 1 hour.",
        "If you did not ask to reset your password, ignore this email. Your password stays the same.",
      ],
      code: { lead: "Or enter this 6-digit code on the reset page:", value: "{{ .Token }}" },
      action: { label: "Reset my password", href: confirmUrl("recovery") },
    },
    SITE,
  ).html;
}
