/**
 * The drawn pictures of VAULTIX: 16 by 16 pixel drawings, one string per row
 * and one character per cell. A space or a dot is transparent; the letters
 * are colours, resolved through `PIXEL_PALETTE` to classes that read semantic
 * tokens, so a drawing never carries a colour value of its own.
 *
 * k ink · p paper · r red · g green · b brass · u blue
 *
 * Original drawings for this product. No logo, artwork or trade dress from any
 * game or brand.
 */
export const PIXEL_PALETTE = {
  k: "resource-emblem__px--ink",
  p: "resource-emblem__px--paper",
  r: "resource-emblem__px--red",
  g: "resource-emblem__px--green",
  b: "resource-emblem__px--brass",
  u: "resource-emblem__px--blue",
} as const;

export type EmblemKind =
  "notes" | "slides" | "exam" | "formula" | "lab" | "worked" | "lost" | "talk";

/** The eight drawings a Wanted shows by itself, from its kind and resource type. */
export const EMBLEM_DRAWINGS: Readonly<Record<EmblemKind, readonly string[]>> = {
  notes: [
    "                ",
    "  kkkkkkkkkkkk  ",
    "  kbpppppppppk  ",
    "  kbpkkkkkkppk  ",
    "  kbpppppppppk  ",
    "  kbpkkkkkkkpk  ",
    "  kbpppppppppk  ",
    "  kbpkkkkkpppk  ",
    "  kbpppppppppk  ",
    "  kbpkkkkkkkpk  ",
    "  kbpppppppppk  ",
    "  kbpkkkkpppgk  ",
    "  kbppppppppgk  ",
    "  kbpppppppggk  ",
    "  kkkkkkkkkkkk  ",
    "                ",
  ],
  slides: [
    "                ",
    " kkkkkkkkkkkkkk ",
    " kppppppppppppk ",
    " kpggggggpppppk ",
    " kppppppppppppk ",
    " kpkkkkkkkkpppk ",
    " kppppppppppppk ",
    " kpkkkkkppprrpk ",
    " kpppppppprrrpk ",
    " kppppppppppppk ",
    " kkkkkkkkkkkkkk ",
    "       kk       ",
    "      k  k      ",
    "     k    k     ",
    "    k      k    ",
    "                ",
  ],
  exam: [
    "                ",
    "  kkkkkkkkkkkk  ",
    "  kbbbbbbbbbbk  ",
    "   kppppppppk   ",
    "   kpkkkkkkpk   ",
    "   kppppppppk   ",
    "   kpkkkkkppk   ",
    "   kppppppppk   ",
    "   kpkkkkkkpk   ",
    "   kpppppprrk   ",
    "   kppppprrrr   ",
    "   kpppppprrk   ",
    "  kbbbbbbbbbbk  ",
    "  kkkkkkkkkkkk  ",
    "                ",
    "                ",
  ],
  formula: [
    "                ",
    "  kkkkkkkkkkkk  ",
    "  kppppppppppk  ",
    "  kpkkkkkkkppk  ",
    "  kppkpppppppk  ",
    "  kpppkppppppk  ",
    "  kppppkpppppk  ",
    "  kpppkppppppk  ",
    "  kppkpppppppk  ",
    "  kpkkkkkkkppk  ",
    "  kppppppppppk  ",
    "  kppbbpbbpbbk  ",
    "  kppppppppppk  ",
    "  kkkkkkkkkkkk  ",
    "                ",
    "                ",
  ],
  lab: [
    "                ",
    "     kkkkkk     ",
    "      kppk      ",
    "      kppk      ",
    "      kppk      ",
    "     kppppk     ",
    "    kppppppk    ",
    "   kppppppppk   ",
    "  kggggggggggk  ",
    "  kgggpggggggk  ",
    " kggggggggpgggk ",
    " kggpgggggggggk ",
    " kggggggggggggk ",
    "  kkkkkkkkkkkk  ",
    "                ",
    "                ",
  ],
  worked: [
    "                ",
    "  kkkkkkkkkk    ",
    "  kppppppppk    ",
    "  kpkkkkkppk    ",
    "  kppppppppk  kk",
    "  kpkkkkkkpk kbk",
    "  kppppppppkkbk ",
    "  kpppppgpkkbk  ",
    "  kppppggpkbk   ",
    "  kpgpggppkk    ",
    "  kpgggpppk     ",
    "  kppgppppk     ",
    "  kppppppppk    ",
    "  kkkkkkkkkk    ",
    "                ",
    "                ",
  ],
  lost: [
    "                ",
    "    kkkkkk      ",
    "   kppppppk     ",
    "  kpbbpppppk    ",
    "  kpbppppppk    ",
    "  kppppppppk    ",
    "  kppppppppk    ",
    "  kppppppppk    ",
    "   kppppppk     ",
    "    kkkkkkrk    ",
    "          krrk  ",
    "           krrk ",
    "            krrk",
    "             kk ",
    "                ",
    "                ",
  ],
  talk: [
    "                ",
    "  kkkkkkkkkkkk  ",
    " kppppppppppppk ",
    " kpkkkkkkkkkppk ",
    " kppppppppppppk ",
    " kpkkkkkkkppppk ",
    " kppppppppppppk ",
    " kpggggpppppppk ",
    " kppppppppppppk ",
    "  kkkkpkkkkkkk  ",
    "     kpk        ",
    "    kpk         ",
    "    kk          ",
    "                ",
    "                ",
    "                ",
  ],
};

export interface PresetPicture {
  readonly name: string;
  readonly rows: readonly string[];
}

/*
 * The fifty pictures a poster may choose for their Wanted. The position in
 * this list is what the database stores (`wanted_pictures.preset`), so a
 * picture is only ever appended: never reorder or remove one.
 */
export const PRESET_PICTURES: readonly PresetPicture[] = [
  { name: "Notebook", rows: EMBLEM_DRAWINGS.notes },
  { name: "Slides", rows: EMBLEM_DRAWINGS.slides },
  { name: "Exam paper", rows: EMBLEM_DRAWINGS.exam },
  { name: "Formula sheet", rows: EMBLEM_DRAWINGS.formula },
  { name: "Flask", rows: EMBLEM_DRAWINGS.lab },
  { name: "Worked answer", rows: EMBLEM_DRAWINGS.worked },
  { name: "Magnifying glass", rows: EMBLEM_DRAWINGS.lost },
  { name: "Speech bubble", rows: EMBLEM_DRAWINGS.talk },
  {
    name: "Open book",
    rows: [
      "................",
      "................",
      "..kkkkk..kkkkk..",
      ".kpppppkkpppppk.",
      ".kpkkkpkkpkkkpk.",
      ".kpppppkkpppppk.",
      ".kpkkkpkkpkkkpk.",
      ".kpppppkkpppppk.",
      ".kpkkppkkpkkppk.",
      ".kpppppkkpppppk.",
      ".kkkkkkrrkkkkkk.",
      "..kbbbbrrbbbbk..",
      "...kkkkkkkkkk...",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "Pencil",
    rows: [
      "................",
      "............kk..",
      "...........krrk.",
      "..........kbkrk.",
      ".........kbbbk..",
      "........kbbbk...",
      ".......kbbbk....",
      "......kbbbk.....",
      ".....kbbbk......",
      "....kbbbk.......",
      "...kpbbk........",
      "..kppkk.........",
      "..kpkk..........",
      "..kk............",
      "................",
      "................",
    ],
  },
  {
    name: "Calculator",
    rows: [
      "................",
      "..kkkkkkkkkkkk..",
      "..kbbbbbbbbbbk..",
      "..kbggggggggbk..",
      "..kbgkgkkgggbk..",
      "..kbggggggggbk..",
      "..kbbbbbbbbbbk..",
      "..kbpkpkpkrkbk..",
      "..kbbbbbbbbbbk..",
      "..kbpkpkpkpkbk..",
      "..kbbbbbbbbbbk..",
      "..kbpkpkpkpkbk..",
      "..kbbbbbbbbbbk..",
      "..kbpkpkpkggbk..",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  {
    name: "Laptop",
    rows: [
      "................",
      "................",
      "...kkkkkkkkkk...",
      "...kuuuuuuuuk...",
      "...kupppuuuuk...",
      "...kuuuuuuuuk...",
      "...kupppppuuk...",
      "...kuuuuuuuuk...",
      "...kuuuuuuuuk...",
      "...kkkkkkkkkk...",
      "..kbbbbbbbbbbk..",
      ".kbbkkkkkkkkbbk.",
      "kkkkkkkkkkkkkkkk",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "Globe",
    rows: [
      "................",
      ".....kkkkkk.....",
      "...kkuuuuuukk...",
      "..kuugguuuuuuk..",
      "..kugggguuuggk..",
      ".kuuggguuuugggk.",
      ".kuuugguuuuuggk.",
      ".kuuuuguuuuuuuk.",
      ".kuuuuuggguuuuk.",
      ".kuuuuggggguuuk.",
      "..kuuuugggguuk..",
      "..kuuuuugguuuk..",
      "...kkuuuuuukk...",
      ".....kkkkkk.....",
      "......kbbk......",
      "....kkkkkkkk....",
    ],
  },
  {
    name: "Atom",
    rows: [
      "................",
      ".......uu.......",
      "......u..u......",
      ".uuu..u..u..uuu.",
      "u...uuu..uuu...u",
      "u....u....u....u",
      ".u...u.rr.u...u.",
      "..u..u.rr.u..u..",
      ".u...u....u...u.",
      "u....u....u....u",
      "u...uuu..uuu...u",
      ".uuu..u..u..uuu.",
      "......u..u......",
      ".......uu.......",
      "................",
      "................",
    ],
  },
  {
    name: "Light bulb",
    rows: [
      "................",
      "......kkkk......",
      "....kkbbbbkk....",
      "...kbbppbbbbk...",
      "...kbppbbbbbk...",
      "..kbbpbbbbbbbk..",
      "..kbbbbbbbbbbk..",
      "..kbbbbkkbbbbk..",
      "...kbbbkkbbbk...",
      "....kbbkkbbk....",
      ".....kbkkbk.....",
      ".....kkkkkk.....",
      ".....kppppk.....",
      ".....kkkkkk.....",
      "......kppk......",
      ".......kk.......",
    ],
  },
  {
    name: "Graduation cap",
    rows: [
      "................",
      "................",
      "................",
      ".......kk.......",
      ".....kkkkkk.....",
      "...kkkkkkkkkk...",
      ".kkkkkkkkkkkkkk.",
      "...kkkkkkkkkkb..",
      "....kkkkkkkk.b..",
      "....kkkkkkkk.b..",
      "....kkkkkkkk.bb.",
      ".....kkkkkk..bb.",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "Trophy",
    rows: [
      "................",
      "...kkkkkkkkkk...",
      ".kkkbbbbbbbbkkk.",
      "kb.kbppbbbbbk.bk",
      "kb.kbpbbbbbbk.bk",
      ".kbkbbbbbbbbkbk.",
      "..kkbbbbbbbbkk..",
      "....kbbbbbbk....",
      ".....kbbbbk.....",
      "......kbbk......",
      ".......kk.......",
      "......kbbk......",
      ".....kkkkkk.....",
      "....kbbbbbbk....",
      "....kkkkkkkk....",
      "................",
    ],
  },
  {
    name: "Star",
    rows: [
      "................",
      ".......kk.......",
      ".......kk.......",
      "......kbbk......",
      "......kbbk......",
      "kkkkkkkbbkkkkkkk",
      ".kbbbbbbbbbbbbk.",
      "..kbbbbbbbbbbk..",
      "...kbbbbbbbbk...",
      "....kbbbbbbk....",
      "....kbbbbbbk....",
      "...kbbbkkbbbk...",
      "...kbbk..kbbk...",
      "..kbk......kbk..",
      "..kk........kk..",
      "................",
    ],
  },
  {
    name: "Horseshoe",
    rows: [
      "................",
      "................",
      "...kkkk..kkkk...",
      "..kbbbk..kbbbk..",
      "..kbpbk..kbpbk..",
      "..kbbbk..kbbbk..",
      "..kbbbk..kbbbk..",
      "..kbpbk..kbpbk..",
      "..kbbbkkkkbbbk..",
      "..kbbbbbbbbbbk..",
      "...kbpbbbbpbk...",
      "....kbbbbbbk....",
      ".....kkkkkk.....",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "Cactus",
    rows: [
      "................",
      ".......kk.......",
      "......kggk......",
      "......kggk......",
      "..kk..kggk......",
      ".kggk.kggk..kk..",
      ".kggk.kggk.kggk.",
      ".kggkkkggk.kggk.",
      "..kggggggkkkggk.",
      "...kkkkggggggk..",
      "......kggkkkk...",
      "......kggk......",
      "......kggk......",
      "....kkkkkkkk....",
      "....krrrrrrk....",
      ".....kkkkkk.....",
    ],
  },
  {
    name: "Cowboy hat",
    rows: [
      "................",
      "................",
      "................",
      "................",
      "......kkkk......",
      ".....kbbbbk.....",
      "....kbbbbbbk....",
      "....kbbkkbbk....",
      "....kbbbbbbk....",
      "....krrrrrrk....",
      "kk..kbbbbbbk..kk",
      "kbkkkkkkkkkkkkbk",
      ".kbbbbbbbbbbbbk.",
      "..kkkkkkkkkkkk..",
      "................",
      "................",
    ],
  },
  {
    name: "Lantern",
    rows: [
      "......kkkk......",
      ".....k....k.....",
      "......kkkk......",
      "....kkkkkkkk....",
      "....kbbbbbbk....",
      "...kbppppppbk...",
      "...kbpprrppbk...",
      "...kbprbbrpbk...",
      "...kbprbbrpbk...",
      "...kbpprrppbk...",
      "...kbppppppbk...",
      "....kbbbbbbk....",
      "....kkkkkkkk....",
      ".....kbbbbk.....",
      "......kkkk......",
      "................",
    ],
  },
  {
    name: "Compass",
    rows: [
      "................",
      ".....kkkkkk.....",
      "...kkppppppkk...",
      "..kpppppkppppk..",
      "..kppppkrkpppk..",
      ".kpppppkrkppppk.",
      ".kpppppkrkppppk.",
      ".kppppkkbkkpppk.",
      ".kpppppkkkppppk.",
      ".kpppppkkkppppk.",
      "..kppppkkkpppk..",
      "..kpppppkppppk..",
      "...kkppppppkk...",
      ".....kkkkkk.....",
      "................",
      "................",
    ],
  },
  {
    name: "Treasure map",
    rows: [
      "................",
      "................",
      ".kkkkkkkkkkkkkk.",
      ".kppppppppppppk.",
      ".kpkppppppppgpk.",
      ".kppkppppppgggk.",
      ".kpppkppppppgpk.",
      ".kpppkppppppppk.",
      ".kppppkkppppppk.",
      ".kpppppppkppppk.",
      ".kppppppppkrprk.",
      ".kpppppppppprpk.",
      ".kppppppppprprk.",
      ".kkkkkkkkkkkkkk.",
      "................",
      "................",
    ],
  },
  {
    name: "Key",
    rows: [
      "................",
      "................",
      "................",
      "..kkkk..........",
      ".kbbbbk.........",
      "kbbkkbbk........",
      "kbk..kbkkkkkkkk.",
      "kbk..kbbbbbbbbbk",
      "kbbkkbbkkkkbkbk.",
      ".kbbbbk....k.k..",
      "..kkkk..........",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "Bounty bag",
    rows: [
      "................",
      "......kkkk......",
      ".......kk.......",
      "......krrk......",
      ".....kkkkkk.....",
      "....kbbbbbbk....",
      "...kbbbbbbbbk...",
      "..kbbbbkkbbbbk..",
      "..kbbbkbbbbbbk..",
      ".kbbbbbkkbbbbbk.",
      ".kbbbbbbbkbbbbk.",
      ".kbbbbbkkbbbbbk.",
      "..kbbbbbbbbbbk..",
      "...kkkkkkkkkk...",
      "................",
      "................",
    ],
  },
  {
    name: "Clock",
    rows: [
      "................",
      ".....kkkkkk.....",
      "...kkppppppkk...",
      "..kppppkpppppk..",
      "..kppppkpppppk..",
      ".kpppppkppppppk.",
      ".kpppppkppppppk.",
      ".kkppppkkkkppkk.",
      ".kppppppppppppk.",
      ".kppppppppppppk.",
      "..kppppppppppk..",
      "..kppppkpppppk..",
      "...kkppppppkk...",
      ".....kkkkkk.....",
      "................",
      "................",
    ],
  },
  {
    name: "Calendar",
    rows: [
      "................",
      "....k......k....",
      "..kkrkkkkkkrkk..",
      "..krrrrrrrrrrk..",
      "..krrrrrrrrrrk..",
      "..kkkkkkkkkkkk..",
      "..kppppppppppk..",
      "..kpkpkpkpkppk..",
      "..kppppppppppk..",
      "..kpkpkpkprppk..",
      "..kppppppppppk..",
      "..kpkpkpkpkppk..",
      "..kppppppppppk..",
      "..kkkkkkkkkkkk..",
      "................",
      "................",
    ],
  },
  {
    name: "Envelope",
    rows: [
      "................",
      "................",
      "................",
      ".kkkkkkkkkkkkkk.",
      ".kkppppppppppkk.",
      ".kpkppppppppkpk.",
      ".kppkppppppkppk.",
      ".kpppkppppkpppk.",
      ".kppppkrrkppppk.",
      ".kpppppkkpppppk.",
      ".kppppppppppppk.",
      ".kppppppppppppk.",
      ".kkkkkkkkkkkkkk.",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "Camera",
    rows: [
      "................",
      "................",
      "................",
      "....kkkk........",
      "...kbbbbk.......",
      ".kkkkkkkkkkkkkk.",
      ".kbbbbkkkkbbbrk.",
      ".kbbbkppppkbbbk.",
      ".kbbkpuuuupkbbk.",
      ".kbbkpuppupkbbk.",
      ".kbbkpuuuupkbbk.",
      ".kbbbkppppkbbbk.",
      ".kbbbbkkkkbbbbk.",
      ".kkkkkkkkkkkkkk.",
      "................",
      "................",
    ],
  },
  {
    name: "Music note",
    rows: [
      "................",
      ".......kkkkkkk..",
      ".......kkkkkkk..",
      ".......k.....k..",
      ".......k.....k..",
      ".......k.....k..",
      ".......k.....k..",
      ".......k.....k..",
      "....kkkk..kkkk..",
      "...kkkkk.kkkkk..",
      "...kkkkk.kkkkk..",
      "....kkk...kkk...",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "Paint palette",
    rows: [
      "................",
      "................",
      ".....kkkkkk.....",
      "...kkbbbbbbkk...",
      "..kbbrrbbbbbbk..",
      ".kbbbrrbbuubbbk.",
      ".kbggbbbbuubbbk.",
      ".kbggbbbbbbbbbk.",
      ".kbbbbbbbkkbbk..",
      ".kbbppbbk..kk...",
      ".kbbppbbk.......",
      "..kbbbbbbk......",
      "...kkkkkk.......",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "Set square",
    rows: [
      "................",
      "..k.............",
      "..kk............",
      "..kbk...........",
      "..kbbk..........",
      "..kbbbk.........",
      "..kbkbbk........",
      "..kbkkbbk.......",
      "..kbbbbbbk......",
      "..kkkkkkkkk.....",
      "................",
      "kkkkkkkkkkkkkkkk",
      "kpkpkpppkpkpkppk",
      "kppppppppppppppk",
      "kkkkkkkkkkkkkkkk",
      "................",
    ],
  },
  {
    name: "Gear",
    rows: [
      "................",
      ".......kk.......",
      "...kk.kbbk.kk...",
      "..kbbkkbbkkbbk..",
      "...kbbbbbbbbk...",
      ".kkbbbbkkbbbbkk.",
      "kbbbbk....kbbbbk",
      ".kkbbk....kbbkk.",
      ".kkbbk....kbbkk.",
      "kbbbbk....kbbbbk",
      ".kkbbbbkkbbbbkk.",
      "...kbbbbbbbbk...",
      "..kbbkkbbkkbbk..",
      "...kk.kbbk.kk...",
      ".......kk.......",
      "................",
    ],
  },
  {
    name: "Microscope",
    rows: [
      "................",
      ".....kkk........",
      ".....kbbk.......",
      "......kbbk......",
      ".......kbbk.....",
      "......kkbbbk....",
      ".....kpk.kbbk...",
      "......k...kbk...",
      "..........kbk...",
      "...kkk....kbk...",
      "..kpppk..kbbk...",
      "...kkkkkkbbk....",
      "......kbbbk.....",
      "...kkkkkkkkkk...",
      "...kbbbbbbbbk...",
      "...kkkkkkkkkk...",
    ],
  },
  {
    name: "Heart",
    rows: [
      "................",
      "................",
      "..kkkk....kkkk..",
      ".krrrrk..krrrrk.",
      "krrpprrkkrrrrrrk",
      "krpprrrrrrrrrrrk",
      "krrrrrrrrrrrrrrk",
      ".krrrrrrrrrrrrk.",
      "..krrrrrrrrrrk..",
      "...krrrrrrrrk...",
      "....krrrrrrk....",
      ".....krrrrk.....",
      "......krrk......",
      ".......kk.......",
      "................",
      "................",
    ],
  },
  {
    name: "Leaf",
    rows: [
      "................",
      "...........kkk..",
      ".........kkgggk.",
      ".......kkgggggk.",
      "......kgggggggk.",
      ".....kgggggggk..",
      "....kggggggpgk..",
      "....kgggggpggk..",
      "...kggggpgggk...",
      "...kgggpggggk...",
      "...kggpgggkk....",
      "...kgpggkk......",
      "..kpkkkk........",
      ".kpk............",
      "kk..............",
      "................",
    ],
  },
  {
    name: "Coffee cup",
    rows: [
      "................",
      "......k..k......",
      ".....k..k.......",
      "......k..k......",
      "................",
      "..kkkkkkkkkk....",
      "..kppppppppkkk..",
      "..kpbbbbbbpk.k..",
      "..kpbbbbbbpk.k..",
      "..kppppppppkkk..",
      "...kppppppk.....",
      "....kkkkkk......",
      ".kkkkkkkkkkkk...",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "Backpack",
    rows: [
      "................",
      "......kkkk......",
      ".....k....k.....",
      "....kkkkkkkk....",
      "...kggggggggk...",
      "..kggggggggggk..",
      "..kggkkkkkkggk..",
      "..kggkbbbbkggk..",
      "..kggkggggkggk..",
      "..kggkkkkkkggk..",
      "..kggggggggggk..",
      "..kggggggggggk..",
      "..kggggggggggk..",
      "...kkkkkkkkkk...",
      "................",
      "................",
    ],
  },
  {
    name: "Umbrella",
    rows: [
      "................",
      ".......kk.......",
      ".....kkrrkk.....",
      "...kkrrrrrrkk...",
      "..krrpprrpprrk..",
      ".krrrpprrpprrrk.",
      ".krrrrrrrrrrrrk.",
      "kkkkkkkkkkkkkkkk",
      ".......kk.......",
      ".......kk.......",
      ".......kk.......",
      ".......kk.......",
      ".......kk..kk...",
      "........kkkk....",
      "................",
      "................",
    ],
  },
  {
    name: "Phone",
    rows: [
      "................",
      ".....kkkkkk.....",
      "....kbbbbbbk....",
      "....kkkkkkkk....",
      "....kuuuuuuk....",
      "....kupppuuk....",
      "....kuuuuuuk....",
      "....kuppppuk....",
      "....kuuuuuuk....",
      "....kuuuuuuk....",
      "....kkkkkkkk....",
      "....kbbkkbbk....",
      "....kbbbbbbk....",
      ".....kkkkkk.....",
      "................",
      "................",
    ],
  },
  {
    name: "Headphones",
    rows: [
      "................",
      "................",
      ".....kkkkkk.....",
      "...kk......kk...",
      "..k..........k..",
      ".k............k.",
      ".k............k.",
      ".k............k.",
      "kkkk........kkkk",
      "krrk........krrk",
      "krrk........krrk",
      "krrk........krrk",
      "kkkk........kkkk",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "Scales",
    rows: [
      "................",
      ".......kk.......",
      "..kkkkkkkkkkkk..",
      "..k....kk....k..",
      ".k.k...kk...k.k.",
      ".k.k...kk...k.k.",
      "k...k..kk..k...k",
      "kbbbk..kk..kbbbk",
      ".kkk...kk...kkk.",
      ".......kk.......",
      ".......kk.......",
      ".......kk.......",
      ".....kkkkkk.....",
      "....kbbbbbbk....",
      "....kkkkkkkk....",
      "................",
    ],
  },
  {
    name: "Wrench",
    rows: [
      "................",
      "..........k..k..",
      "..........kbbk..",
      ".........kbbbk..",
      "........kbbkk...",
      ".......kbbk.....",
      "......kbbk......",
      ".....kbbk.......",
      "....kbbk........",
      "...kbbk.........",
      "..kbbk..........",
      ".kbbbbk.........",
      ".kbkkbk.........",
      "..k..k..........",
      "................",
      "................",
    ],
  },
  {
    name: "Magnet",
    rows: [
      "................",
      "..kkkk....kkkk..",
      "..kppk....kppk..",
      "..kkkk....kkkk..",
      "..krrk....krrk..",
      "..krrk....krrk..",
      "..krrk....krrk..",
      "..krrk....krrk..",
      "..krrkkkkkkrrk..",
      "..krrrrrrrrrrk..",
      "...krrrrrrrrk...",
      "....kkkkkkkk....",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  {
    name: "Rocket",
    rows: [
      ".......kk.......",
      "......krrk......",
      ".....krrrrk.....",
      ".....kppppk.....",
      ".....kpuupk.....",
      ".....kpuupk.....",
      ".....kppppk.....",
      ".....kppppk.....",
      "....kkppppkk....",
      "...krkppppkrk...",
      "..krrkppppkrrk..",
      "..kkkkkkkkkkkk..",
      "......kbbk......",
      ".....kbrrbk.....",
      "......krrk......",
      ".......kk.......",
    ],
  },
  {
    name: "Moon and stars",
    rows: [
      "................",
      ".....kkkk.......",
      "...kkbbk........",
      "..kbbbk.....b...",
      ".kbbbk.....bbb..",
      ".kbbk.......b...",
      "kbbbk...........",
      "kbbbk...........",
      "kbbbk.....b.....",
      "kbbbbk..........",
      ".kbbbbbkk....kk.",
      "..kbbbbbbkkkkbk.",
      "...kkbbbbbbbbk..",
      ".....kkkkkkkk...",
      "................",
      "................",
    ],
  },
  {
    name: "Sun",
    rows: [
      "................",
      ".......b........",
      "..b....b....b...",
      "...b.......b....",
      ".....kkkkk......",
      "....kbbbbbk.....",
      "...kbbbbbbbk....",
      "bb.kbbbbbbbk.bb.",
      "...kbbbbbbbk....",
      "...kbbbbbbbk....",
      "....kbbbbbk.....",
      ".....kkkkk......",
      "...b.......b....",
      "..b....b....b...",
      ".......b........",
      "................",
    ],
  },
  {
    name: "Rain cloud",
    rows: [
      "................",
      "................",
      ".....kkkk.......",
      "....kppppk.kk...",
      "..kkkppppkkppk..",
      ".kppppppppppppk.",
      "kppppppppppppppk",
      "kppppppppppppppk",
      ".kkkkkkkkkkkkkk.",
      "................",
      "..u...u...u...u.",
      ".u...u...u...u..",
      "................",
      "...u...u...u....",
      "..u...u...u.....",
      "................",
    ],
  },
  {
    name: "Cat",
    rows: [
      "................",
      "..kk........kk..",
      "..kbk......kbk..",
      "..kbbkkkkkkbbk..",
      "..kbbbbbbbbbbk..",
      ".kbbbbbbbbbbbbk.",
      ".kbbkgkbbkgkbbk.",
      ".kbbkkkbbkkkbbk.",
      ".kbbbbbbbbbbbbk.",
      "kkbbbbbrrbbbbbkk",
      ".kbbbbbkkbbbbbk.",
      "..kbbbbbbbbbbk..",
      "...kkkkkkkkkk...",
      "................",
      "................",
      "................",
    ],
  },
];
